### ISSUE TITLE
Add issue templates

### ISSUE THREAD

**Issue by AndreTerra5348** [AndreTerra5348/appointment#37]
### Description
- The templates shall be located at .github/ISSUE_TEMPLATE

### Tasks
- [x] Template for high level specification
- [x] Template for low level specification
- [x] Template for bug report
- [x] Template for general task
