### ISSUE TITLE
Add missing tests

### ISSUE THREAD

**Issue by AndreTerra5348** [AndreTerra5348/appointment#45]
### Description
- Add missing tests for files with low coverage

### Tasks
- [x] [lib/infrastructure/client/table.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/infrastructure/client/table.dart)
- [x] [lib/infrastructure/drift/native_db.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/infrastructure/drift/native_db.dart)
- [x] [lib/application/common/form.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/application/common/form.dart)
- [x] [lib/application/client/search/status.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/application/client/search/status.dart)
- [x] [lib/application/delete/bloc/state.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/application/delete/bloc/state.dart)
- [x] [lib/application/edit/bloc/state.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/application/edit/bloc/state.dart)
- [x] [lib/presentation/config/route.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/presentation/config/route.dart)
- [x] [lib/application/load/bloc/state.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/application/load/bloc/state.dart)
- [x] [lib/domain/common/entity_mixin.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/domain/common/entity_mixin.dart)
- [x] [lib/presentation/common/failure_extensions.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/presentation/common/failure_extensions.dart)
