### ISSUE TITLE
Remove configuration files from test coverage

### ISSUE THREAD

**Issue by AndreTerra5348** [AndreTerra5348/appointment#46]
### Description
- Add `// coverage:ignore-file` to files that should be ignored

### Tasks
- [ ] [lib/presentation/config/di.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/presentation/config/di.dart)
- [ ] [lib/presentation/config/route.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/presentation/config/route.dart)
- [ ] [lib/infrastructure/client/table.dart](https://app.codecov.io/gh/AndreTerra5348/appointment/blob/main/lib/infrastructure/client/table.dart)
