### ISSUE TITLE
Fix test files location

### ISSUE THREAD

**Issue by AndreTerra5348** [AndreTerra5348/appointment#57]
### Tasks
- [x] Change `test\domain\common_errors_test.dart` to `test\domain\common\common_errors_test.dart`
- [x] Change `test\infrastructure\client\page_service_test.dart` to `test\infrastructure\core\page_service_test.dart`
- [x] Change `test\infrastructure\client\drift_repository_test.dart` to `test\infrastructure\core\drift_repository_test.dart`
- [x] Change `test\infrastructure\native_db_factory_test.dart` to `test\infrastructure\drift\native_db_factory_test.dart`
